name: Coverage-and-Autodoc

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  build:
    name: Build the package
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
           python-version: "3.10"

      # Runs a single command using the runners shell
      - name: Install dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  autodoc:
    name: >-
        Create autodoc and gh-page
    needs: 
        - build
    runs-on: ubuntu-latest
    
    steps:
      # checkout required to access repository code?!
    - uses: actions/checkout@v4
    - name: Build HTML
      run: | 
        cd docs/
        sphinx-apidoc -o ../docs ../phaser
        make html

    - name: Run ghp-import
      run: | 
        ghp-import -n -p -f docs/_build/html